config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :coach_students
  root "users#index"

end

app/models/coach_student.rb
class CoachStudent < ActiveRecord::Base
	# creates the relationships where User 'coach' & 'student' can be found by 'coach_id' & 'student_id'
	belongs_to :user
	belongs_to :student, class_name: 'User', foreign_key: 'student_id'

end

app/models/user.rb
class User < ActiveRecord::Base
	# relates Users through coach_students table
	has_many :coach_students
	has_many :students, through: :coach_students

	# will allow for a user to get their students.
	def coaches_student?(student)
		students.include?(student)
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coach_students_controller.rb
class CoachStudentsController < ApplicationController

  # used for the form for adding the coach student relationship
	def new
		if params[:student_id] && params[:user_id]
      @user = User.where(id: params[:user_id]).first
			@student = User.where(id: params[:student_id]).first
			@coach_student = CoachStudent.new(student: @student, user: @user)
		else
			flash[:error] = "Sorry there is and error in the CoachStudentsController-new"
		end

	rescue ActiveRecord::RecordNotFound
		render file: 'public/404', status: :not_found
	end


  # creates the actual relationship. 
  def create
    if params[:coach_student] && params[:coach_student].has_key?(:student_id) && params[:coach_student].has_key?(:user_id)
      @user = User.where(id: params[:user_id]).first
		  @student = User.where(id: params[:student_id]).first
		  @coach_student = CoachStudent.new(coach_params)

    if @coach_student.save
        flash[:notice] = "Student Added!"
      else
        flash[:notice] = "There was a problem adding this student."
      end
      # redirects the coach who added the student
      redirect_to user_path(@coach_student.user_id)
    else
      flash[:notice] = "Student required."
      redirect_to root_path
    end

  end

  private

  def coach_params
    params.require(:coach_student).permit(:user_id, :student_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
    @user = User.new

  end

  # GET /users/1/edit
  def edit
  end

  def show
    @users = User.all
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { redirect_to root_path, notice: 'There was a problem creating this user, please try again.' }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
      
      # !!!!!!! This is the infect method !!!!!!!!
      # If a user is the student of the user who is getting a :site_version change, 
      # the student user will also be changed to that version.

       User.all.each do |student| 
         while @user.coaches_student?(student) 
           student.update(site_version: @user.site_version)
           # changes the user to the student to change the version of their students as well.
           @user = student 
         end
       end 


        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :site_version)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coach_students_helper.rb
module CoachStudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coach_students/new.html.erb
<div class="student_confirm">
	<% if @coach_student %>

		<%= simple_form_for(@coach_student) do |f| %>
			<div>
				<!-- gets the params throught he controller and sets the values for relationship -->
				<%= f.hidden_field :user_id, value: @user.id %>
				<%= f.hidden_field :student_id, value: @student.id %>

				Are you sure you want to add <strong><%=@student.user_name%></strong> as one of your students?
				<br>
				<%= link_to "Cancel", :back %>
				<%= f.submit "Yes, Add Student"%>

			</div>

		<% end %>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infection</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- displays the notices -->
<% flash.each do |message| %>
	<div class="">
		<%= message %>
	</div>
<% end %>


<%= yield %>


</body>
</html>

app/views/users/_form.html.erb
<!-- The form for creating a new user-->
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div>
    <%= f.input :user_name, label: 'Create a New User', placeholder: "Enter a Name" %>
    <%= f.hidden_field :site_version, value: "1.0" %>

    <%= f.submit "Add User" %>
  </div>

  
<% end %>

app/views/users/edit.html.erb
<!-- links back to the main page -->
<%= link_to "Back", :back %>

<!-- the form where the users site_version can be updated -->
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  	<div class="padding">
  		<%= @user.user_name%> is currently on version: <strong><%= @user.site_version %></strong>
  	</div>
	<div class="update_version">
		<%= f.input :user_name, value: @user, label: "Name" %>

	    <%= f.input :site_version, label: "Enter the new version name below." %>

	    
	   	<% User.all.each do |student| %>
	   		<% if @user.coaches_student?(student) %>
	   			<strong><%= student.user_name %></strong><em> Will also be updated.</em><br>
	   		<% end%>

	   	<% end %>


	    <%= f.submit "Update" %>
    </div>
  
<% end %>

app/views/users/index.html.erb
<h1>Infection</h1>

<!-- Link to add a new user -->
<div class="add_new_user_form">
  <%= render 'form' %>
</div>

<!-- Will show a list of all the users -->
<h2>Current Users</h2>
<% @users.each do |user| %>

  <div class="users_list">
<!-- can delete user  -->

    <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'right' %>
    
<!-- Displays the users information -->

    <h3><%= user.user_name %></h3>
    Current Version: <strong><%= user.site_version%></strong>
    <br><br>
<!-- will render the buttons to change version and add students -->

    <div class="padding">
      <%= link_to "Change Version", edit_user_path(user), class: "button" %>
      <%= link_to "Add Student", user_path(user), class: "button" %>
    </div>

<!-- will display all the users students and version -->

    <h4>Total Students: <%= user.students.count %></h4>
    <div>
      <% user.students.all.each do |student| %>
        <ul>
          <li><%= student.user_name %>, Version: <%= student.site_version %></li>
        </ul>
      <% end %>
    </div>

  </div>

<% end %>

app/views/users/show.html.erb
<%= link_to "home", root_path %>

<h1><%= @user.user_name %> </h1> 
<h3> Version: <%= @user.site_version%></h3>

 <%= link_to "Change Your Version", edit_user_path(@user), class: "button" %>

<br>
<br>
<h2>Add Students</h2>
<% @users.each do |student| %>
	<div class ="student_list">
		<% if @user.coaches_student?(student) %>
			<%= link_to student.user_name, user_path(student) %>
			<span class="right">
				<strong>Student</strong> <em>on verson: <%=student.site_version%></em>
			</span>
		<% else %>
			<%= link_to student.user_name, user_path(student) %>
			<%= link_to "add", new_coach_student_path(user_id: @user, student_id: student), 
												  data: { user_id: @user.id, student_id: student.id }, class: "right"%>
		<% end %>										  
	</div>
<% end %>